---
title: "bird_joins"
author: "Meagan Brown"
date: '2022-08-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(lubridate)
```


```{r}
bird_observations <- read_csv(here("data", "52_pp52_birds_1.csv"))
sites <- read_csv(here("data", "52_pp52_sites_1.csv"))
surveys <- read_csv(here("data", "52_pp52_surveys_1.csv"))
taxalist <- read_csv(here("data", "52_pp52_taxalist_1.csv"))
```

```{r}
birds_subset <- bird_observations %>% 
  filter(species_id %in% c("BHCO",
                           "RWBL") &
         site_id %in% c("LI-W",
                        "NU-C")) 

```

```{r}
# Use left join(s) to update birds_subset so that it also includes sites and taxalist information. For each join, include an explicit argument saying which variable you are joining by (even if it will just assume the correct one for you). Store the updated data frame as birds_left. Make sure to look at the output - is what it contains consistent with what you expected it to contain?

birds_left <- left_join(birds_subset, 
                        sites, 
                        taxalist, 
                        by = "site_id")
```

```{r}
# Write code to full_join the birds_subset and sites data into a new object called birds_full. Explicitly include the variable you’re joining by. Look at the output. Is it what you expected?
birds_full <- full_join(birds_subset, sites)
```

```{r}
# Write code to inner_join() the birds_subset and taxalist, called birds_inner. Include an argument for what variable you’ll be joining by.

birds_inner <- inner_join(birds_subset, taxalist,
                          by = "species_id")

```

```{r}
# Starting with your birds object, rename the notes column to bird_obs_notes (so this doesn’t conflict with notes in the surveys dataset

birds <- bird_observations %>% 
  rename("bird_obs_notes" = notes)

# Then, create a subset that contains all observations in the birds dataset, joins the taxonomic, site and survey information to it, and is finally limited to only columns survey_date, common_name, park_name, and bird_count. You can decide the order that you want to create this in (e.g. limit the columns first, then join, or the other way around).

birds_subset2 <- birds %>% 
  left_join(taxalist, by = "species_id") %>% 
  left_join(sites, by = "site_id") %>% 
  left_join(surveys, by = "site_id") %>% 
  select(survey_date, 
         common_name, 
         park_name, 
         bird_count) %>% 

# Use lubridate::month() to add a new column called survey_month, containing only the month number. Then, convert the month number to a factor (again within mutate())
mutate(survey_date = ymd(survey_date)) %>% 
mutate(survey_month = month(survey_date)) %>% 

# Learn a new function on your own! Use dplyr::relocate() to move the new survey_month column to immediately after the survey_date column. You can do this in a separate code chunk, or pipe straight into it from your existing code.

relocate(survey_month, .after = survey_date) 

# Find the total number of birds observed by park and month (i.e., you’ll group_by(park_name, survey_month))

birds_observed <- birds_subset2 %>% 
  group_by(park_name, survey_month) %>% 
  summarize(bird_count = sum(bird_count, na.rm = TRUE)) %>% 

# Filter to only include parks “Lindo”, “Orme”, “Palomino” and “Sonrisa”
filter(park_name %in% c("Lindo",
                        "Orme",
                        "Palomino",
                        "Sonrisa"))
```

